### ISSUE TITLE
number stations et destination N/A

### ISSUE THREAD

**Issue by tet102** [da4throux/MMM-Paris-RATP-PG#21]
Hello, I try MMM-Paris-RATP-PG and it's very good function for MM, but it's never give any information for line {type:.....with stations and destination.
eg:
{type: 'metros', line: '6', stations: 145, destination: 17},
{type: 'rers', line: 'B', stations: 62, destination: 4},

1) Where do you find number station and desitnation please ?
2) Why do I have on my mirror ?
6N/A... 
BN/A....

Thank you for you answer. 
Stéphane

**Comment by da4throux** [comment]
Hi Stéphane,

(you can switch to French if you prefer).
1. you can find the instruction in the README.txt, the bulletpoint describing 'busStations' [basically it relies on Pierre Grimaud interface, which itself relies on RATP API] If you are still struggling with finding, I can guide you find one specific station as an example if you want.
2. I think v2 is now deprecated, so you should switch to v3, and add: api: 'v3' (you can see example at the end of the README.txt). I'll probably remove everything pointing to v2 in a next version, as it seems now deprecated.

Hope that help,
Damien

**Comment by tet102** [comment]
Hi Damien, Thank you, for your answer.
I I've already read docs of Pierre Grimaud, but i never find any information which give  number station and number destination of each metro line of paris.
I ve an example : I'm at Duroc station on line metro 13 and my desitnation is "Les courtilles".
On my config.js i write:
{type: 'metros', line: '13', stations: ???, destination: ??},    
{api: 'v3', type: 'metros', line: '13', stations: 'Duroc', destination: 'A'},
NB: I don't write ??? but i write stations: 145, destination: 17 (but it's wrong- I take number of line 6).
MagicMirror display:
13N/A
13genneviliers  4min/5min

If you can tell me  how to find these informations ?
Thank you for your help, Best regards.

**Comment by da4throux** [comment]
Hi,

I think you are doing it write, somehow you are making two calls:
 - one to the v2 api which is now deprecated and get you the N/A
 - and the second one that seems fine: next train on line 13 to Genneviliers being 4 mins and 5 minutes away.
I'll clean up the v2 mention in my next iteration to avoid further confusion.

The line 13 is forking (St Denis on one side and Asnieres on the other side), the interface does not help here to separate the two, so we get the next direction of the next train, but not the one of the following one... (unless it improved since I last looked at it).
This was better in v2, especially for buses that sometimes do not go up to their final stop.

Just in case: reading the Readme.txt and using v3:
1. I request all the lines: https://api-ratp.pierre-grimaud.fr/v3/lines/metros
2. I see:
      {
        "code": "13",
        "name": "Métro 13",
        "directions": "St-Denis-Universite/Les Courtilles / Chatillon - Montrouge",
        "id": "66"
      },
3. Check the stations: https://api-ratp.pierre-grimaud.fr/v3/stations/metros/13
4. I see: 
 {
                "slug": "duroc",
                "name": "Duroc"
            },
So in the config it should be:
{api: 'v3', type: 'metros', line:'13', stations:'duroc', destination:'A'}

I think you are good, or do you need something else,
Damien

**Comment by tet102** [comment]
Salut Damien, 
thank you for your help and i found a good config.js, see my config below.
Now i have the name of my station.on the line.
Stephane.

{
		        module: 'MMM-Paris-RATP-PG',
		        position: 'center',
	        	header: 'Connections',
		        config: {
				    busStations:[						
						{api: 'v3', type: 'metros', line: '13', stations: 'Duroc', destination: 'A', label:'13 Duroc vers'},
						{api: 'v3', type: 'metros', line: '8', stations: 'Invalides', destination: 'R', label:'8 Invalides vers'},
						{api: 'v3', type: 'traffic', line: ['metros', '8']}
						      ]
			        }
	    	},
