### ISSUE TITLE
MMM-Paris-RATP-PG - Paris Issue with Loading connections

### ISSUE THREAD

**Issue by sdrouet** [da4throux/MMM-Paris-RATP-PG#35]
Hello,

I am experiencing an issue with the MMM-Paris-RATP-PG - Paris module. Seems like my config file is good (I used one given by da4throux) but even with this config I have a "Loading connections" on my screen. All other modules are working fine as they are getting info from internet. But whatever config i do for the MMM-Paris-RATP-PG - Paris, I only have a loading connections.

Does someone else can help me in this?

Thanks a lot

**Comment by da4throux** [comment]
Hi,

if you could post or send me your config (the simpler the better), plus the logs (server side) that would be ideal to start understanding the issue.
Is it your first time using the module ?

thanks

**Comment by sdrouet** [comment]
Hello back,

Seems like it is ok :). Once I modified the config file, I have to relaunch the app. A simple reload of the magicmirror screen doesn't work. For other default modules it works but not for yours. Dunno why. Thanks a lot by the way for being prompt to answer me

**Comment by sdrouet** [comment]
Just a question regarding the output. Seems that when I try to recover the schedule for the RER A from Houilles Carrière sur Seine it says schedule unavailable... Does someone know why?

**Comment by sdrouet** [comment]
https://api-ratp.pierre-grimaud.fr/v4/schedules/rers/a/houilles+carrieres+sur+seine/R

**Comment by da4throux** [comment]
No idea for the houilles station, it seems it's not the only station. I wonder if it's linked to the strike, or you noticed this behavior before ?

Regarding the reloading, it's probably due to the fact that all the API fetching is done from the "app" (the server side), while the browser is mainly displaying. I initialize the server at the start of the app with the config file received from the browser (in MMM the server side is not required for a module). So that would explain what you saw.
I'll add that comment to the readme file so that it's clearer.

**Comment by sdrouet** [comment]
I don't think that it's linked to the strike. Currently even when the RER A is working it is still displaying "Schedule unavailable". And yes you are right it's not the only one station.

Do you think that it can be resolved somehow?

**Comment by da4throux** [comment]
Maybe try directly the RATP API to see if the wrong data comes from there, else contact Pierre Grimaud ( https://github.com/pgrimaud/horaires-ratp-api ) ?
